[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://scarlettcordova-quema-grasa-constru.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
